title: "Comunicar usando Markdown"
description: "This course will walk you through everything you need to start organizing ideas and collaborating using Markdown, a lightweight language for text formatting."
template:
  name: "portafolio-markdown"
  repo: "comunicar-usando-markdown-plantilla"
preferences:
  - type: radio
    name: gitTool
    label: Preferred Git tool
    description: You can follow this course's instructions using whichever Git tool you prefer.
    options:
      - label: GitHub.com
        value: dotcom
      - label: Command line
        value: cli
tags: [
  "GitHub","Markdown"
]
before:
  - type: updateBranchProtection
    branch: master
    enforce_admins: true
    required_pull_request_reviews:
      include_admins: true
  - type: createIssue
    title: Empezar a usar GitHub
    body: "00_welcome.md"
    comments:
      - "00_create-tasklist.md"
steps:
  #1 - Create a task list
  - title: "Crear una lista de tareas"
    description: "Aprende acerca de las listas de tareas en tu primera propuesta."
    event: "issue_comment.created"
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: gate
        left: '(-|\*)\s+\[[x|X|\s]\]\s+.+'
        operator: test
        right: '%payload.comment.body%'
        else:
          - type: gate
            left: '(-|\*)\s+\[[x|X|\s]+\]\s+.+'
            operator: test
            right: '%payload.comment.body%'
            else:
              - type: respond
                with: '01_tasklist.md'
          - type: respond
            with: '01_taskwhitespaces.md'
      - type: respond
        with: '01_turn-on-ghp.md'

  #2 - Turn on GitHub Pages
  - title: "Activa GitHub Pages"
    description: "Implementa los contenidos de tu repositorio mediante GitHub Pages para crear tu sitio web."
    event: page_build
    link: '{{ repoUrl }}/settings'
    actions:
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: createPullRequest
        action_id: pr
        title: Añade un encabezado a tu portafolio
        body: '02_headers.md'
        head: add-headers
        data:
          thePayload: '%payload%'
      - type: closeIssue
        issue: Empezar a usar GitHub
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        issue: Empezar a usar GitHub
        with: '02_close-issue.md'
        data:
          url: '%actions.pagesUrl.data.html_url%'
          prUrl: '%actions.pr.data.html_url%'

  #3 - Add headers
  - title: "Añadir encabezados"
    description: "Añade encabezados a un contenido sin formato."
    event: "pull_request.synchronize"
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: '_includes/01-name.md'
      - type: gate
        left: '/^#{1,6}\s.+/gm'
        operator: test
        right: '%actions.fileContents%'
        else:
          type: respond
          with: 03_request-changes.md
      - type: removeBranchProtection
      - type: respond
        with: 03_pr-succeeds.md

  #4 - Merge your headers
  - title: "Combina tus encabezados"
    description: "Combina tu primera solicitud de extracción para ver los encabezados en acción."
    event: "pull_request.closed"
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: updateBranchProtection
      - type: createPullRequest
        action_id: pr
        title: Preséntante al mundo
        body: 04_add-image.md
        head: add-images-links
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        with: 04_next.md
        data:
          url: '%actions.pagesUrl.data.html_url%'
          prUrl: '%actions.pr.data.html_url%'

  #5 - Add an image
  - title: "Añade una imagen"
    description: "Aprende a usar imágenes en Markdown añadiendo tu foto."
    event: "pull_request.synchronize"
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: getFileContents
        filename: '_includes/02-image.md'
        action_id: fileContents
      - type: gate
        left: '/!\[.+\]\(.+\)/g'
        operator: test
        right: '%actions.fileContents%'
        else:
          type: respond
          with: 05_request-changes-image.md
      - type: respond
        with: 05_image-works-url.md

  #6 - Add a profile link
  - title: "Añade un enlace a tu perfil"
    description: "Aprende cómo crear enlaces en Markdown."
    event: "pull_request.synchronize"
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: getFileContents
        filename: '_includes/03-links.md'
        action_id: fileContents
      - type: gate
        left: '/!?\[.+\]\(.+\)/g'
        operator: test
        right: '%actions.fileContents%'
        else:
          type: respond
          with: 06_request-changes-link.md
      - type: removeBranchProtection
      - type: respond
        with: 06_success.md

    #7 - Merge your image and link
  - title: "Combina tu imagen y tu enlace"
    description: "Combina tu segunda solicitud de extracción para presentarte al mundo."
    event: "pull_request.closed"
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: updateBranchProtection
      - type: createPullRequest
        title: Algunas de tus cosas favoritas
        body: 07_pr-body.md
        action_id: pr
        head: add-lists-emphasis
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        with: 07_next.md
        data:
          url: '%actions.pagesUrl.data.html_url%'
          prUrl: '%actions.pr.data.html_url%'

  #8 - Add a list
  - title: "Añade una lista"
    description: "Aprende cómo crear listas ordenadas y desordenadas."
    event: "pull_request.synchronize"
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: getFileContents
        filename: '_includes/04-lists.md'
        action_id: fileContents
      - type: gate
        left: '/(?:\d\.|\*|-)\s.+/gm'
        operator: test
        right: '%actions.fileContents%'
        else:
          type: respond
          with: 08_request-changes.md
      - type: respond
        with: 08_emphasis.md

  #9 - Use emphasis
  - title: "Usa énfasis"
    description: "Utiliza negritas y cursivas para destacar texto."
    event: "pull_request.synchronize"
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: getFileContents
        filename: '_includes/05-emphasis.md'
        action_id: fileContents
      - type: gate
        left: '/([*|_]{1,2}).+\1/gm'
        operator: test
        right: '%actions.fileContents%'
        else:
          type: respond
          with: 09_request-changes.md
      - type: removeBranchProtection
      - type: respond
        with: 09_success.md

  #10 - Merge lists and  emphasis
  - title: "Combina las listas y el énfasis"
    description: "Combina los últimos cambios a tu portafolio."
    event: "pull_request.closed"
    link: '{{ repoUrl }}/pull/4'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createIssue
        title: Más para aprender
        body: 10_more-to-learn.md
        action_id: issue
      - type: mergeBranch
        head: add-theme
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        with: 10_next.md
        data:
          url: '%actions.pagesUrl.data.html_url%'
          issueUrl: '%actions.issue.data.html_url%'
      - type: octokit
        method: repos.update
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        name: '%payload.repository.name%'
        homepage: 'https://%payload.repository.owner.login%.github.io/%payload.repository.name%'
